---
# tasks file for role-gitlab
- name: Prepare directory for shared folders
  file:
    path: "{{gitlab_dir}}"
    state: directory
  when:
    - gitlab_dir != false

- name: Run GitLab
  register: gitlab
  docker_container:
    image: "{{gitlab_container.image}}"
    links: "{{gitlab_container.links}}"
    name: "{{gitlab_container.name}}"
    ports: "{{gitlab_container.ports}}"
    pull: yes
    recreate: "{{gitlab_container.recreate}}"
    restart: "{{gitlab_container.restart}}"
    restart_policy: "{{gitlab_container.restart_policy}}"
    state: started
    volumes: "{{gitlab_container.volumes}}"

- name: Wait until GitLab started
  delay: "{{gitlab_container_check_delay}}"
  ignore_errors: yes
  register: result
  retries: "{{gitlab_container_check_retries}}"
  until: result.status == 200
  uri:
    follow_redirects: safe
    status_code: 200
    url: "{{gitlab_container_check_url}}"
  when:
    - gitlab.changed
    - gitlab_container_check_url != false

- name: Setup GitLab config
  become: yes
  copy:
    content: "{{gitlab_config}}"
    dest: "{{gitlab_config_dest}}"
  notify:
    - Reload GitLab
  when:
    - gitlab_config != false

- meta: flush_handlers
